---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jonas-lernia-app
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ghcr.io/ainadevops/lernia-app2:latest
    importPolicy:
      importMode: Legacy
      scheduled: true
    name: latest
    referencePolicy:
      type: Source

